
31. How many transactions were made using each payment method?
32. What is the total revenue generated by each payment method?
33. What is the average transaction value for each payment method?
34. Which payment method has the highest transaction volume?
35. Which payment method generates the highest revenue?
36. What is the distribution of transaction status?
37. What is the revenue by transaction status?
38. Which payment method has the highest number of cancelled/failed/pending transactions?
39. What percentage of transactions are completed?
40. What percentage of transactions are missing transaction status?