Product Analysis
11. What is the total revenue generated by each product?
12. Which products have the highest number of transactions?
13. Which products have the highest quantity sold?
14. What is the average selling price of each product?
15. What is the average quantity purchased for each product?
16. Which products generate the highest average transaction value?
17. Which products have low sales volume?
18. What percentage of total revenue comes from each product?
19. How many unique customers purchased each product?
20. Which products have the highest number of repeat customers?